name: Codeball AI Code Review

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Codeball AI Code Review
      uses: sturdy-dev/codeball-action@v2.6.0
